In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
iris=load_iris()

In [2]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [3]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
df['target']=iris.target
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [5]:
df['target']=df['target'].apply(lambda x:iris.target_names[x])
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [6]:
df[67:80]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
67,5.8,2.7,4.1,1.0,versicolor
68,6.2,2.2,4.5,1.5,versicolor
69,5.6,2.5,3.9,1.1,versicolor
70,5.9,3.2,4.8,1.8,versicolor
71,6.1,2.8,4.0,1.3,versicolor
72,6.3,2.5,4.9,1.5,versicolor
73,6.1,2.8,4.7,1.2,versicolor
74,6.4,2.9,4.3,1.3,versicolor
75,6.6,3.0,4.4,1.4,versicolor
76,6.8,2.8,4.8,1.4,versicolor
77,6.7,3.0,5.0,1.7,versicolor
78,6.0,2.9,4.5,1.5,versicolor
79,5.7,2.6,3.5,1.0,versicolor

In [7]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(iris.data,iris.target,test_size=0.3)

In [8]:
#using support vector machine
from sklearn.svm import SVC
m_svc=SVC(kernel='rbf',C=20,gamma='auto')
m_svc.fit(xtrain,ytrain)
m_svc.score(xtest,ytest)

0.9555555555555556

In [9]:
#using KFold cross validation
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),xtest,ytest,cv=5)

array([1.        , 0.88888889, 1.        , 1.        , 0.88888889])

In [10]:
cross_val_score(SVC(kernel='poly',C=20,gamma='auto'),xtest,ytest,cv=5)

array([1.        , 0.88888889, 1.        , 1.        , 0.88888889])

In [11]:
cross_val_score(SVC(kernel='linear',C=30,gamma='auto'),xtest,ytest,cv=5)

array([1.        , 0.88888889, 1.        , 0.88888889, 0.88888889])

In [12]:
#by SVM Model
kernals=['rbf','linear']
C=[1,10,20]
avg_score={}
for kval in kernals:
    for cval in C:
        cv=cross_val_score(SVC(kernel=kval,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg_score[kval + '_' + str(cval)]=np.average(cv)
avg_score

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [13]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(SVC(gamma='auto'), {
    'C': np.arange(1,10),
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)
clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00119128, 0.00020061, 0.0038794 , 0.00020876, 0.        ,
        0.00118151, 0.00139365, 0.00127363, 0.00053496, 0.00059409,
        0.00150385, 0.00019979, 0.        , 0.00449276, 0.00126481,
        0.00165377, 0.00061421, 0.00019927]),
 'std_fit_time': array([0.00098862, 0.00040121, 0.00486369, 0.00041752, 0.        ,
        0.00027461, 0.00088378, 0.00072984, 0.00044444, 0.00078836,
        0.00129829, 0.00039959, 0.        , 0.00580977, 0.00252962,
        0.00330753, 0.00082594, 0.00039854]),
 'mean_score_time': array([8.76617432e-04, 1.99413300e-04, 1.58977509e-04, 1.32861137e-03,
        0.00000000e+00, 5.88941574e-04, 4.85992432e-04, 2.45618820e-04,
        6.60467148e-04, 1.54023170e-03, 1.99890137e-04, 0.00000000e+00,
        0.00000000e+00, 4.05263901e-04, 2.11286545e-04, 2.41756439e-05,
        1.61571503e-03, 1.04441643e-03]),
 'std_score_time': array([9.50850089e-04, 3.98826599e-04, 3.17955017e-04, 2.65722275e-03,
        0.00000000e+00, 4.81363188e-04, 6.04529677e-04, 4.91237640e-04,
        5.39574702e-04, 1.71675129e-03, 3.99780273e-04, 0.00000000e+00,
        0.00000000e+00, 4.96449233e-04, 4.22573090e-04, 4.83512878e-05,
        2.75972927e-03, 1.32374110e-03]),
 'param_C': masked_array(data=[1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 2, 'kernel': 'rbf'},
  {'C': 2, 'kernel': 'linear'},
  {'C': 3, 'kernel': 'rbf'},
  {'C': 3, 'kernel': 'linear'},
  {'C': 4, 'kernel': 'rbf'},
  {'C': 4, 'kernel': 'linear'},
  {'C': 5, 'kernel': 'rbf'},
  {'C': 5, 'kernel': 'linear'},
  {'C': 6, 'kernel': 'rbf'},
  {'C': 6, 'kernel': 'linear'},
  {'C': 7, 'kernel': 'rbf'},
  {'C': 7, 'kernel': 'linear'},
  {'C': 8, 'kernel': 'rbf'},
  {'C': 8, 'kernel': 'linear'},
  {'C': 9, 'kernel': 'rbf'},
  {'C': 9, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 1.        ,
        0.96666667, 1.        , 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.93333333, 1.        , 0.93333333, 0.96666667, 0.93333333,
        0.96666667, 0.9       , 0.96666667, 0.9       , 0.96666667,
        0.9       , 0.96666667, 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.98      , 0.97333333,
        0.97333333, 0.98666667, 0.97333333, 0.98      , 0.98      ,
        0.98      , 0.97333333, 0.98      , 0.97333333, 0.98      ,
        0.97333333, 0.98      , 0.97333333]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.01632993, 0.02494438,
        0.02494438, 0.01632993, 0.02494438, 0.01632993, 0.02666667,
        0.01632993, 0.03887301, 0.01632993, 0.03887301, 0.01632993,
        0.03887301, 0.01632993, 0.03887301]),
 'rank_test_score': array([ 2,  2,  2,  2, 12, 12,  1, 12,  2,  2,  2, 12,  2, 12,  2, 12,  2,
        12])}

In [14]:
df=pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001191,0.000989,0.000877,0.000951,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
1,0.000201,0.000401,0.000199,0.000399,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
2,0.003879,0.004864,0.000159,0.000318,2,rbf,"{'C': 2, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
3,0.000209,0.000418,0.001329,0.002657,2,linear,"{'C': 2, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
4,0.000000,0.000000,0.000000,0.000000,3,rbf,"{'C': 3, 'kernel': 'rbf'}",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,12
5,0.001182,0.000275,0.000589,0.000481,3,linear,"{'C': 3, 'kernel': 'linear'}",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,12
6,0.001394,0.000884,0.000486,0.000605,4,rbf,"{'C': 4, 'kernel': 'rbf'}",0.966667,1.0,1.000000,0.966667,1.0,0.986667,0.016330,1
7,0.001274,0.000730,0.000246,0.000491,4,linear,"{'C': 4, 'kernel': 'linear'}",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,12
8,0.000535,0.000444,0.000660,0.000540,5,rbf,"{'C': 5, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
9,0.000594,0.000788,0.001540,0.001717,5,linear,"{'C': 5, 'kernel': 'linear'}",1.000000,1.0,0.933333,0.966667,1.0,0.980000,0.026667,2
10,0.001504,0.001298,0.000200,0.000400,6,rbf,"{'C': 6, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
11,0.000200,0.000400,0.000000,0.000000,6,linear,"{'C': 6, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,12
12,0.000000,0.000000,0.000000,0.000000,7,rbf,"{'C': 7, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
13,0.004493,0.005810,0.000405,0.000496,7,linear,"{'C': 7, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,12
14,0.001265,0.002530,0.000211,0.000423,8,rbf,"{'C': 8, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
15,0.001654,0.003308,0.000024,0.000048,8,linear,"{'C': 8, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,12
16,0.000614,0.000826,0.001616,0.002760,9,rbf,"{'C': 9, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
17,0.000199,0.000399,0.001044,0.001324,9,linear,"{'C': 9, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,12

In [15]:
df[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2        2          rbf         0.980000
3        2       linear         0.980000
4        3          rbf         0.973333
5        3       linear         0.973333
6        4          rbf         0.986667
7        4       linear         0.973333
8        5          rbf         0.980000
9        5       linear         0.980000
10       6          rbf         0.980000
11       6       linear         0.973333
12       7          rbf         0.980000
13       7       linear         0.973333
14       8          rbf         0.980000
15       8       linear         0.973333
16       9          rbf         0.980000
17       9       linear         0.973333

In [16]:
clf.best_estimator_

SVC(C=4, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [17]:
clf.best_params_

{'C': 4, 'kernel': 'rbf'}

In [18]:
clf.best_score_

0.9866666666666667

In [19]:
clf.best_index_

6

In [20]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=2
)
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1       linear             0.98
1       1          rbf             0.98

In [21]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [27]:
model_params = {
    'svm': {
        'model': SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,10,20]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,10,20]
        }
    }
}

In [28]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

                 model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000       {'n_estimators': 10}
2  logistic_regression    0.966667                  {'C': 10}

In [26]:
#Based on above, I can conclude that SVM with C=1 and kernel='rbf' is the best model for solving my problem of iris flower classification